name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      PYTHONDONTWRITEBYTECODE: true
      PYTHONPATH: test_project
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          # cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -e "."
          python -m pip install -e ".[test]"

      - name: Lint with flake8
        run: |
          flake8 . --ignore=E501,E402
