name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      PYTHONDONTWRITEBYTECODE: true
      PYTHONPATH: test_project
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: '**/setup.cfg'

      - name: Install dependencies
        run: |
          python -m pip install uv
          python -m uv pip install --system -e "."
          python -m uv pip install --system -e ".[test]"

      - name: Lint with flake8
        run: |
          flake8 . --ignore=E501,E402
